#!/usr/bin/env python
# Usage:       conda activate pila
#              python generate_classical_jobs.py
# Description: Write ONE PBS job per exported_ml5/*.mat so the 21 classical SA+MCMC inversions
#              run in PARALLEL (vs the single sequential submit_classical_all_ml5.pbs). Each job
#              sets CFG=<ConfigName> and runs classical_rerun/rerun_one_ml5.m. Walltime/mem are
#              scaled by point count (Nyiragongo TD21 ~101k pts is by far the heaviest).
#              GENERATES ONLY -- review, then qsub. Output of the runs -> classic_out_ml5/<cfg>/.
# Date:        2026-06-25

import os
import glob
import argparse
from scipy.io import loadmat

REPO = os.path.dirname(os.path.abspath(__file__))

PBS_TEMPLATE = """#!/bin/bash
# Usage:       qsub {pbs_basename}
# Description: Classical SA+MCMC inversion for {cfg} (ml=5, N={n}, model={model}) on exported_ml5/.
#              One config per job (parallel). Generated by generate_classical_jobs.py.
# Date:        2026-06-25
#PBS -N {job_name}
#PBS -P eos_btaisne
#PBS -q qintel_wfly
#PBS -l nodes=1:ppn=4
#PBS -l walltime={walltime}
#PBS -l mem={mem}
#PBS -j oe
#PBS -o logs/{job_name}_pbs.log

cd "$PBS_O_WORKDIR"
# Non-interactive PBS shell lacks the `module` function until its init is sourced.
source /usr/local/Modules/init/bash
module load matlab/R2023b-u9
command -v matlab >/dev/null || {{ echo "ERROR: matlab not on PATH after module load"; exit 1; }}

export CFG="{cfg}"
export EXPORT_DIR="{exported}"
export OUT_DIR="{out_dir}"
echo "[{job_name}] CFG=$CFG  EXPORT_DIR=$EXPORT_DIR  OUT_DIR=$OUT_DIR  host=$(hostname)  N={n}  $(date)"
matlab -nodisplay -nosplash -batch "run('classical_rerun/rerun_one_ml5.m')"
echo "[{job_name}] done $(date)"
"""


def scale_resources(n):
    """Walltime/mem by point count: MCMC cost grows with N (Nyiragongo TD21 ~101k dominates)."""
    if n > 80000:
        return '24:00:00', '32gb'
    if n > 40000:
        return '16:00:00', '24gb'
    return '08:00:00', '16gb'


def short_name(cfg, prefix):
    # PBS job name <= 15 chars, e.g. CL5_NyOkTD21 / CL20_NyOkTD21
    parts = cfg.split('_')
    vol = parts[0][:2]
    mod = parts[1][:2] if len(parts) > 1 else ''
    trk = parts[2] if len(parts) > 2 else ''
    return f'{prefix}_{vol}{mod}{trk}'[:15]


def main():
    ap = argparse.ArgumentParser(description="Generate one classical PBS job per exported config")
    ap.add_argument('--exported', default='exported_ml5',
                    help="Dir of exported <cfg>.mat (passed to MATLAB as EXPORT_DIR).")
    ap.add_argument('--out-dir', default='classic_out_ml5',
                    help="Classical output root (passed to MATLAB as OUT_DIR).")
    ap.add_argument('--pbs-out', default='classical_rerun/jobs_ml5')
    ap.add_argument('--prefix', default=None,
                    help="PBS job-name prefix (default CL20 if 'ml20' in --exported else CL5).")
    args = ap.parse_args()
    prefix = args.prefix or ('CL20' if 'ml20' in args.exported else 'CL5')
    pbs_tag = prefix.lower()

    pbs_out = os.path.join(REPO, args.pbs_out)
    os.makedirs(pbs_out, exist_ok=True)

    mats = sorted(glob.glob(os.path.join(REPO, args.exported, '*.mat')))
    if not mats:
        raise FileNotFoundError(f"No .mat in {args.exported}/ (run export_pila_points.py first)")

    submit_cmds = []
    for m in mats:
        cfg = os.path.splitext(os.path.basename(m))[0]
        E = loadmat(m)
        n = int(E['n_points'][0, 0])
        model = str(E['model'][0])
        walltime, mem = scale_resources(n)
        job_name = short_name(cfg, prefix)
        pbs_basename = f'{pbs_tag}_{cfg.lower()}.pbs'
        pbs_path = os.path.join(pbs_out, pbs_basename)
        with open(pbs_path, 'w') as fh:
            fh.write(PBS_TEMPLATE.format(
                pbs_basename=pbs_basename, cfg=cfg, n=n, model=model,
                job_name=job_name, walltime=walltime, mem=mem,
                exported=args.exported, out_dir=args.out_dir))
        submit_cmds.append(f"qsub {os.path.relpath(pbs_path, REPO)}")

    print(f"Wrote {len(submit_cmds)} per-config classical PBS jobs to {args.pbs_out}/")
    print("Submit all (review first):")
    for c in submit_cmds:
        print(f"  {c}")


if __name__ == '__main__':
    main()
