#!/usr/bin/env python
# Usage:       conda activate pila
#              python generate_multistart_jobs.py [--seeds 1 2 3 4 5] [--multilook 5]
# Description: Multi-start re-fit of ALL 21 production full-scene configs (LaPalma/Etna/
#              Nyiragongo Mogi+Sun69+Okada x2 tracks + SierraNegra Mogi/Sun69/Okada InSAR_A).
#              A single deterministic PILA run can fall into a poor local minimum on noisy real
#              scenes (Okada collapses to a null source, opening=0; Mogi/Sun69 can land on a
#              worse fit). This generates one config + PBS job per (config, seed): same data +
#              each config's own prior, only the RNG seed (--seed) varies. select_multistart.py
#              then keeps the best-R2 run per config. GENERATES ONLY -- review, then qsub.
# Date:        2026-06-24

import os
import json
import argparse

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))

ALL_CONFIGS = [
    # LaPalma (TA60, TD169) x Mogi/Sun69/Okada
    'LaPalma_Mogi_TA60_A', 'LaPalma_Mogi_TD169_A',
    'LaPalma_Sun69_TA60_A', 'LaPalma_Sun69_TD169_A',
    'LaPalma_Okada_TA60_A', 'LaPalma_Okada_TD169_A',
    # Etna (TA44, TD124) x Mogi/Sun69/Okada
    'Etna_Mogi_TA44_A', 'Etna_Mogi_TD124_A',
    'Etna_Sun69_TA44_A', 'Etna_Sun69_TD124_A',
    'Etna_Okada_TA44_A', 'Etna_Okada_TD124_A',
    # Nyiragongo (TA174, TD21) x Mogi/Sun69/Okada
    'Nyiragongo_Mogi_TA174_A', 'Nyiragongo_Mogi_TD21_A',
    'Nyiragongo_Sun69_TA174_A', 'Nyiragongo_Sun69_TD21_A',
    'Nyiragongo_Okada_TA174_A', 'Nyiragongo_Okada_TD21_A',
    # SierraNegra (InSAR_A) x Mogi/Sun69/Okada
    'SierraNegra_Mogi_InSAR_A', 'SierraNegra_Sun69_InSAR_A', 'SierraNegra_Okada_InSAR_A',
]

PBS_TEMPLATE = """#!/bin/bash
# Usage:       qsub {pbs_basename}
# Description: Multi-start member for {name} (seed {seed}) at multilook={ml}, config's own prior.
#              Generated by generate_multistart_jobs.py -- do not edit by hand.
# Date:        2026-06-24
#PBS -N {job_name}
#PBS -P eos_btaisne
#PBS -q qintel_wfly
#PBS -l nodes=1:ppn=4
#PBS -l walltime=06:00:00
#PBS -l mem={mem}
#PBS -j oe
#PBS -o logs/{job_name}_pbs.log

cd "$PBS_O_WORKDIR"
source /eos-rs/miniconda3/etc/profile.d/conda.sh
conda activate pila
export PYTHONPATH="${{PYTHONPATH}}:$PBS_O_WORKDIR"

echo "[{job_name}] seed={seed}  host=$(hostname)  $(date)"
python train_pila.py --config {config_rel} --seed {seed}
echo "[{job_name}] done $(date)"
"""


def set_multilook_everywhere(cfg, ml):
    arch_ins = cfg['arch']['args'].get('insar')
    if arch_ins is not None:
        arch_ins['multilook'] = ml
    dl = cfg.get('data_loader', {})
    for block in (dl.get('args', {}), dl.get('data_dir_valid', {}), dl.get('data_dir_test', {})):
        if isinstance(block, dict):
            if isinstance(block.get('insar'), dict):
                block['insar']['multilook'] = ml
            elif 'timeseries' in block:
                block['multilook'] = ml


def main():
    ap = argparse.ArgumentParser(description="Generate multi-start Okada re-fit jobs")
    ap.add_argument('--seeds', type=int, nargs='+', default=[1, 2, 3, 4, 5])
    ap.add_argument('--multilook', type=int, default=5)
    ap.add_argument('--cfg-out', default='configs/phys_smpl/multistart')
    ap.add_argument('--pbs-out', default='multistart_jobs')
    ap.add_argument('--save-root', default='saved/multistart')
    args = ap.parse_args()

    cfg_out = os.path.join(REPO_ROOT, args.cfg_out)
    pbs_out = os.path.join(REPO_ROOT, args.pbs_out)
    os.makedirs(cfg_out, exist_ok=True)
    os.makedirs(pbs_out, exist_ok=True)

    submit_cmds = []
    for base in ALL_CONFIGS:
        src = os.path.join(REPO_ROOT, 'configs', 'phys_smpl', f'{base}.json')
        with open(src) as fh:
            base_cfg = json.load(fh)
        mem = '128gb' if 'TD21' in base else '64gb'  # TD21 is the heaviest (~100k pts at ML5)
        for seed in args.seeds:
            cfg = json.loads(json.dumps(base_cfg))   # deep copy
            set_multilook_everywhere(cfg, args.multilook)
            cfg['seed'] = int(seed)
            cfg['trainer']['save_dir'] = f"{args.save_root}/{base.lower()}_s{seed}"
            cfg_path = os.path.join(cfg_out, f'{base}_s{seed}.json')
            with open(cfg_path, 'w') as fh:
                json.dump(cfg, fh, indent=1)
            cfg_rel = os.path.relpath(cfg_path, REPO_ROOT)

            # PBS job name <= 15 chars: e.g. MS_ETOKTD124_s3
            short = ''.join(p[0] for p in base.split('_') if p)  # EOTA / EOTD / NOTA / NOTD-ish
            job_name = f'MS_{short}{base.split("_")[-2]}_s{seed}'[:15]
            pbs_basename = f'ms_{base.lower()}_s{seed}.pbs'
            pbs_path = os.path.join(pbs_out, pbs_basename)
            with open(pbs_path, 'w') as fh:
                fh.write(PBS_TEMPLATE.format(
                    pbs_basename=pbs_basename, name=base, seed=seed, ml=args.multilook,
                    job_name=job_name, mem=mem, config_rel=cfg_rel))
            submit_cmds.append(f"qsub {os.path.relpath(pbs_path, REPO_ROOT)}")

    print(f"Wrote {len(submit_cmds)} (config x seed) jobs "
          f"({len(ALL_CONFIGS)} configs x {len(args.seeds)} seeds) "
          f"to {args.cfg_out}/ and {args.pbs_out}/")
    print("Submit all (review first):")
    for c in submit_cmds:
        print(f"  {c}")


if __name__ == '__main__':
    main()
