#!/usr/bin/env python
# Usage:       conda activate pila
#              python generate_definitive_jobs.py [--multilook 5]
# Description: Generate the DEFINITIVE full-scene PILA configs + PBS submit scripts for the
#              5 InSAR runs (4 Okada + SierraNegra Sun69), at a light multilook, using the
#              CURRENT (post-okada-fix) working-tree code. Each new config is a copy of the
#              canonical configs/phys_smpl/<Name>.json with (a) multilook set in ALL four
#              insar blocks and (b) trainer.save_dir redirected to saved/full_scene_def/ so
#              the existing saved/full_scene/ (multilook=20) runs are NEVER overwritten.
#              GENERATES ONLY -- it never calls qsub. Review the scripts, then submit.
# Date:        2026-06-24

import os
import json
import argparse

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))

# (config basename, PBS job name <=15 chars, PBS mem) -- mem sized for FULL-RESOLUTION
# (multilook=1) point counts: 0.7M-2.5M cells -> 90M-326M encoder params + Adam state.
# TD21 (2.5M cells) is by far the heaviest; Sierra (1.4M) next.
RUNS = [
    ('Etna_Okada_TA44_A',        'DEF_ET_OK_TA44',  '64gb'),   # ~0.83M cells
    ('Etna_Okada_TD124_A',       'DEF_ET_OK_TD124', '64gb'),   # ~0.71M cells
    ('Nyiragongo_Okada_TA174_A', 'DEF_NY_OK_TA174', '64gb'),   # ~0.92M cells
    ('Nyiragongo_Okada_TD21_A',  'DEF_NY_OK_TD21',  '128gb'),  # ~2.5M cells -> heaviest
    ('SierraNegra_Sun69_InSAR_A','DEF_SN_SUN69',    '96gb'),   # ~1.4M cells
]

PBS_PROJECT = 'eos_btaisne'
PBS_QUEUE = 'qintel_wfly'
PPN = 8
WALLTIME = '24:00:00'

PBS_TEMPLATE = """#!/bin/bash
# Usage:       qsub {pbs_basename}
# Description: DEFINITIVE full-scene PILA run for {name} at multilook={ml} (post-okada-fix
#              code). Trains on the whole MintPy LOS time series; saves to
#              saved/full_scene_def/. Generated by generate_definitive_jobs.py -- do not
#              edit by hand; re-run the generator instead.
# Date:        2026-06-24
#PBS -N {job_name}
#PBS -P {project}
#PBS -q {queue}
#PBS -l nodes=1:ppn={ppn}
#PBS -l walltime={walltime}
#PBS -l mem={mem}
#PBS -j oe
#PBS -o logs/{job_name}_pbs.log

# --- Move to the directory the job was submitted from (the PILA repo root) ---
cd "$PBS_O_WORKDIR"

# --- Activate the PILA conda environment (torch 2.0.0, CPU-only on this node) ---
source /eos-rs/miniconda3/etc/profile.d/conda.sh
conda activate pila

# --- Make the repo importable (data_loader, model, datasets, ... are top-level pkgs) ---
export PYTHONPATH="${{PYTHONPATH}}:$PBS_O_WORKDIR"

echo "[{job_name}] Host: $(hostname)  Env: $CONDA_DEFAULT_ENV  Workdir: $PBS_O_WORKDIR"
echo "[{job_name}] Starting DEFINITIVE training (multilook={ml}) at $(date)"

# --- Train the definitive full-scene model (multilook baked into the config) ---
python train_pila.py --config {config_rel}

echo "[{job_name}] Finished at $(date)"
"""


def set_multilook_everywhere(cfg, ml):
    """Set insar.multilook=ml in every insar block (arch + loader args + valid/test)."""
    arch_ins = cfg['arch']['args'].get('insar')
    if arch_ins is not None:
        arch_ins['multilook'] = ml
    dl = cfg.get('data_loader', {})
    for block in (dl.get('args', {}), dl.get('data_dir_valid', {}), dl.get('data_dir_test', {})):
        if isinstance(block, dict):
            if isinstance(block.get('insar'), dict):
                block['insar']['multilook'] = ml
            elif 'timeseries' in block:
                block['multilook'] = ml


def main():
    ap = argparse.ArgumentParser(description="Generate definitive full-scene PILA jobs")
    ap.add_argument('--multilook', type=int, default=5, help="block-average factor (default 5)")
    ap.add_argument('--cfg-out', default='configs/phys_smpl/definitive')
    ap.add_argument('--pbs-out', default='definitive_jobs')
    ap.add_argument('--save-root', default='saved/full_scene_def')
    args = ap.parse_args()

    cfg_out = os.path.join(REPO_ROOT, args.cfg_out)
    pbs_out = os.path.join(REPO_ROOT, args.pbs_out)
    os.makedirs(cfg_out, exist_ok=True)
    os.makedirs(pbs_out, exist_ok=True)

    print(f"[1/2] Writing {len(RUNS)} definitive configs (multilook={args.multilook}) ...")
    submit_cmds = []
    for base, job_name, mem in RUNS:
        src = os.path.join(REPO_ROOT, 'configs', 'phys_smpl', f'{base}.json')
        with open(src) as fh:
            cfg = json.load(fh)
        set_multilook_everywhere(cfg, args.multilook)
        # Redirect output so the existing saved/full_scene/ (ML=20) runs are untouched.
        cfg['trainer']['save_dir'] = f"{args.save_root}/{base.lower()}"
        cfg_path = os.path.join(cfg_out, f'{base}.json')
        with open(cfg_path, 'w') as fh:
            json.dump(cfg, fh, indent=1)
        cfg_rel = os.path.relpath(cfg_path, REPO_ROOT)

        pbs_basename = f'submit_definitive_{base.lower()}.pbs'
        pbs_path = os.path.join(pbs_out, pbs_basename)
        with open(pbs_path, 'w') as fh:
            fh.write(PBS_TEMPLATE.format(
                pbs_basename=pbs_basename, name=base, ml=args.multilook,
                job_name=job_name, project=PBS_PROJECT, queue=PBS_QUEUE,
                ppn=PPN, walltime=WALLTIME, mem=mem, config_rel=cfg_rel))
        submit_cmds.append(f"qsub {os.path.relpath(pbs_path, REPO_ROOT)}")
        print(f"  {base:28s} -> {cfg_rel}  | {pbs_basename}  (mem={mem})")

    print(f"\n[2/2] Wrote {len(RUNS)} configs to {args.cfg_out}/ and {len(RUNS)} PBS scripts "
          f"to {args.pbs_out}/")
    print("\nTo submit ALL (review first!):")
    for c in submit_cmds:
        print(f"  {c}")
    print("\nNOTE: this script GENERATES ONLY -- it does not qsub anything.")


if __name__ == '__main__':
    main()
