#!/usr/bin/env python
# Usage:       python generate_uq_jobs.py --base-config configs/phys_smpl/Etna_Mogi_TA44_A.json --stride 5
#              python generate_uq_jobs.py --base-config <cfg> --stride 5 --multilook 1
# Description: Build a strided-decimation UNCERTAINTY-QUANTIFICATION ensemble for PILA.
#              Given ONE base InSAR config and a stride n, writes n derived configs +
#              n PBS submit scripts -- ensemble member m (offset 0..n-1) trains on every
#              n-th coherent pixel starting at index m. The n subsets are disjoint and
#              jointly tile the full coherent grid; the spread of the inverted source
#              parameters across the n members is the uncertainty estimate.
#              GENERATES ONLY -- it never calls qsub. Review the scripts, then submit
#              the printed commands yourself.
# Date:        2026-06-23
#
# Scientific assumptions / caveats (flagged for the user):
#   * DEFAULT multilook=1 (full resolution). Striding REPLACES multilooking as the data-
#     reduction step. Each member sees ~N/n full-res (un-averaged, hence noisier) cells.
#   * Per-member input_dim ~= N/n. Full-resolution scenes can have very large N, so each
#     member's MLP encoder width and physics forward scale with N/n -- choose n large
#     enough to keep N/n in the hundreds-to-few-thousand, or pass --multilook >1 to combine
#     a light multilook with striding if full-res is too heavy. The realized per-member
#     point count is printed by the loader at run time and saved in compute_usage.json.
#   * Standardization is PER-SUBSET (each member's x_mean/x_scale come from its own points,
#     a deliberate choice), so a small amount of scaler variability enters the spread.
#   * This is SYSTEMATIC decimation with a fixed K=n, not a random bootstrap. The spread
#     reflects sensitivity to which pixels are sampled.

import argparse
import copy
import json
import os
import re

# --- Paths -----------------------------------------------------------------
REPO_ROOT = "/eos-rs/INSAR_processing/denny/PILA"
PBS_PROJECT = "eos_btaisne"
PBS_QUEUE = "qintel_wfly"


def set_insar_uq(cfg, multilook, stride, offset):
    """
    Stamp the UQ/decimation keys into EVERY insar block of a config dict (in place).

    Two block shapes exist (see train_pila._propagate_insar_uq): data_loader.args wraps
    the insar dict under an 'insar' key; data_dir_valid / data_dir_test ARE the insar dict
    directly. arch.args.insar is the canonical block. All must agree so the dataset and the
    physics decoder invert the SAME pixel subset.
    """
    uq = {"multilook": int(multilook), "stride": int(stride), "offset": int(offset)}

    arch_ins = cfg.get("arch", {}).get("args", {}).get("insar")
    if not isinstance(arch_ins, dict):
        raise ValueError("base config has no arch.args.insar block -- not an InSAR config?")
    arch_ins.update(uq)

    dl = cfg.get("data_loader", {})
    for block in (dl.get("args", {}), dl.get("data_dir_valid", {}), dl.get("data_dir_test", {})):
        if not isinstance(block, dict):
            continue
        if isinstance(block.get("insar"), dict):     # wrapped (data_loader.args.insar)
            block["insar"].update(uq)
        elif "timeseries" in block:                  # bare insar dict (valid/test)
            block.update(uq)


def build_pbs(job_name, config_rel_path, ppn, walltime, mem):
    """Build one PBS submit-script string that trains a single ensemble member."""
    return f"""#!/bin/bash
# Usage:       qsub {os.path.basename(config_rel_path).replace('.json', '.pbs')}
# Description: Train one PILA UQ ensemble member (strided-decimation subset). Generated by
#              generate_uq_jobs.py -- do not edit by hand; re-run the generator instead.
# Date:        2026-06-23
#PBS -N {job_name}
#PBS -P {PBS_PROJECT}
#PBS -q {PBS_QUEUE}
#PBS -l nodes=1:ppn={ppn}
#PBS -l walltime={walltime}
#PBS -l mem={mem}
#PBS -j oe
#PBS -o logs/{job_name}_pbs.log

# --- Move to the directory the job was submitted from (the PILA repo root) ---
cd "$PBS_O_WORKDIR"

# --- Activate the PILA conda environment ---
source /eos-rs/miniconda3/etc/profile.d/conda.sh
conda activate pila

# --- Make the repo importable (data_loader, model, datasets, ... are top-level pkgs) ---
export PYTHONPATH="${{PYTHONPATH}}:$PBS_O_WORKDIR"

echo "[{job_name}] Host: $(hostname)  Env: $CONDA_DEFAULT_ENV  Workdir: $PBS_O_WORKDIR"
echo "[{job_name}] Starting at $(date)"

# --- Train this ensemble member (stride/offset already baked into the config) ---
python train_pila.py --config {config_rel_path}

echo "[{job_name}] Finished at $(date)"
"""


def main():
    parser = argparse.ArgumentParser(description="Generate a PILA strided-decimation UQ ensemble")
    parser.add_argument("--base-config", required=True,
                        help="path to an existing InSAR config JSON to template from")
    parser.add_argument("--stride", required=True, type=int,
                        help="decimation factor n -> ensemble of n members (offsets 0..n-1)")
    parser.add_argument("--multilook", type=int, default=1,
                        help="multilook factor (default 1 = full resolution; striding "
                             "replaces multilooking). Use >1 to combine a light multilook.")
    parser.add_argument("--out-config-dir", default=os.path.join(REPO_ROOT, "configs", "phys_smpl", "uq"),
                        help="directory for the n derived configs")
    parser.add_argument("--out-pbs-dir", default=REPO_ROOT,
                        help="directory for the n PBS submit scripts")
    # Per-job PBS resources. Defaults are sized for small strided members (~minutes,
    # ~1 core, a few GB); raise them for large-N (small-stride) members.
    parser.add_argument("--ppn", type=int, default=2, help="cores per job (default 2)")
    parser.add_argument("--walltime", default="02:00:00", help="PBS walltime (default 02:00:00)")
    parser.add_argument("--mem", default="8gb", help="PBS mem per job (default 8gb)")
    args = parser.parse_args()

    if args.stride < 2:
        parser.error(f"--stride must be >= 2 to form an ensemble (got {args.stride})")

    base_path = args.base_config if os.path.isabs(args.base_config) else os.path.join(REPO_ROOT, args.base_config)
    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    print(f"[1/3] Loading base config: {base_path}")
    with open(base_path) as fh:
        base_cfg = json.load(fh)
    base_name = base_cfg.get("name", os.path.splitext(os.path.basename(base_path))[0])
    print(f"  Base name: {base_name}; stride n={args.stride}, multilook={args.multilook}")

    os.makedirs(args.out_config_dir, exist_ok=True)
    os.makedirs(args.out_pbs_dir, exist_ok=True)
    os.makedirs(os.path.join(REPO_ROOT, "logs"), exist_ok=True)

    # PBS-safe (<=15 char) job stem. Keep the full TRACK token (e.g. TA44 / TD124) so
    # ascending vs descending members are distinguishable in qstat -- using only first
    # letters collapses TA44 and TD124 both to 'T', making the two tracks look identical.
    parts = base_name.split("_")
    track = next((p for p in parts if re.match(r'^T[A-Z]*\d+$', p)), None)
    prefix = "".join(p[0] for p in parts if p and p != track).upper()
    stem = (prefix + (track or "")).upper()

    print(f"[2/3] Writing {args.stride} member configs + PBS scripts ...")
    submit_cmds = []
    for offset in range(args.stride):
        cfg = copy.deepcopy(base_cfg)
        member_name = f"{base_name}_uqstr{args.stride}_off{offset}"
        set_insar_uq(cfg, args.multilook, args.stride, offset)
        cfg["name"] = member_name
        # All members of one ensemble share a save_dir ROOT under saved/stride_uq/ (kept
        # separate from full-scene runs in saved/full_scene/). ConfigParser then nests each
        # member under its own exper_name (member_name, carrying the offset) + timestamp, so
        # the n members never collide and the aggregator globs them as <root>/*.
        stride_root = f"saved/stride_uq/{base_name.lower()}_uqstr{args.stride}"
        cfg["trainer"]["save_dir"] = stride_root

        cfg_path = os.path.join(args.out_config_dir, f"{member_name}.json")
        with open(cfg_path, "w") as fh:
            json.dump(cfg, fh, indent=4)

        cfg_rel = os.path.relpath(cfg_path, REPO_ROOT)
        job_name = f"{stem}s{args.stride}o{offset}"[:15]
        pbs_path = os.path.join(args.out_pbs_dir, f"submit_{member_name.lower()}.pbs")
        with open(pbs_path, "w") as fh:
            fh.write(build_pbs(job_name, cfg_rel, args.ppn, args.walltime, args.mem))
        submit_cmds.append(f"qsub {os.path.relpath(pbs_path, REPO_ROOT)}")

    print(f"  Wrote {args.stride} configs to {args.out_config_dir}")
    print(f"  Wrote {args.stride} PBS scripts to {args.out_pbs_dir}")

    print("[3/3] Done. Review the scripts, then submit the ensemble (NOT submitted for you):")
    for c in submit_cmds:
        print("  " + c)
    print(f"\nAfter all {args.stride} members finish, aggregate with:")
    print(f"  python aggregate_uq.py "
          f"--runs-glob 'saved/stride_uq/{base_name.lower()}_uqstr{args.stride}/*' "
          f"--name {base_name}_uqstr{args.stride}")


if __name__ == "__main__":
    main()
