#!/bin/bash
# Train one PILA block-bootstrap UQ ensemble sequentially on CPU.
# Generated by generate_bootstrap_jobs.py -- marapi_okada_dike_mid_combined_bootk819_b3, B=20.
set -e
cd "$(dirname "$0")"
source /eos-rs/miniconda3/etc/profile.d/conda.sh
conda activate pila
export PYTHONPATH="${PYTHONPATH}:$(pwd)"
echo "[bootstrap 1/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off0.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off0.json
echo "[bootstrap 2/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off1.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off1.json
echo "[bootstrap 3/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off2.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off2.json
echo "[bootstrap 4/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off3.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off3.json
echo "[bootstrap 5/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off4.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off4.json
echo "[bootstrap 6/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off5.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off5.json
echo "[bootstrap 7/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off6.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off6.json
echo "[bootstrap 8/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off7.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off7.json
echo "[bootstrap 9/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off8.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off8.json
echo "[bootstrap 10/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off9.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off9.json
echo "[bootstrap 11/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off10.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off10.json
echo "[bootstrap 12/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off11.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off11.json
echo "[bootstrap 13/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off12.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off12.json
echo "[bootstrap 14/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off13.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off13.json
echo "[bootstrap 15/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off14.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off14.json
echo "[bootstrap 16/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off15.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off15.json
echo "[bootstrap 17/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off16.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off16.json
echo "[bootstrap 18/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off17.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off17.json
echo "[bootstrap 19/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off18.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off18.json
echo "[bootstrap 20/20] training configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off19.json"
python train_pila.py --config configs/phys_smpl/bootstrap/marapi_okada_dike_mid_combined_bootk819_b3_off19.json
echo "All bootstrap members trained."
